; PlatformIO Project Configuration File

[platformio]
default_envs = core_esp32dev
boards_dir = boards

[env]
platform = espressif32@6.11.0
framework = espidf
upload_speed = 921600
monitor_speed = 115200
monitor_filters = time, esp32_exception_decoder

[env:core_esp32dev]
board = esp32dev
board_build.partitions = partitions_core.csv
